{
    'name': 'Fusion Sync',
    'version': '0.1.18',
    'category': 'Manufacturing',
    'summary': 'Synchronize Fusion 360 designs with Odoo',
    'author': 'Jaco',
    'website': 'https://jaco.tech',
    'company': 'Jacotech',
    'license': 'AGPL-3',
    'depends': ['base', 'mrp'],
    'data': [
        'security/fusion_security.xml',
        'security/ir.model.access.csv',
        'data/fusion_component_sequence.xml',
        'views/fusion_component_views.xml',
        'views/fusion_user_views.xml',
        'views/fusion_component_version_views.xml',
        'views/fusion_component_version_assembly_line_views.xml',
        'views/fusion_design_views.xml',
        'views/fusion_design_version_views.xml',
        'views/fusion_menus.xml',
    ],
    'installable': True,
    'application': True,
    'sequence': 1,
}
